### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by kingoftheconnors**
Updated documentation to take recent changes into account and also add more advice to help editting the config file.

### CODE REVIEW

**Comment by jeffcasavant** [comment]
That config update should probably also go in https://github.com/matrix-hacks/matrix-puppet-groupme/blob/master/index.js - add a line like 132, but with the regex for the aliases.  And actually once it's there I don't think it'd need to be in the readme.

**Comment by kingoftheconnors** [comment]
See above change.

**Comment by jeffcasavant** [comment]
I have been attempting to run this GroupMe bridge for the longest time and was getting no message traffic across it.  @kingoftheconnors found that the aliases list was still empty.  Updating it to the value this PR makes the bridge generate fixed the problem and now I am successfully bridging messages back & forth.

**Comment by thomas-profitt** [comment]
Thank you!

Improving documentation across our bridges is seriously appreciated; they're much too difficult to set up than they should be.

And a big thank you for fixing the alias reservation issue! I had been meaning to check and see if matrix-puppet-bridge bridges other than matrix-puppet-slack implemented the fix for newer Synapse versions, and I see that this bridge was missing its update, so thanks!

**Pull request merged**
